from building import *

cwd = GetCurrentDir()

src = []
path = []

if GetDepend('TINYSQUARE_USING_EXAMPLES_SNAKE'):
    src += Glob('snake/*.c')
    path += [cwd + '/snake']

if GetDepend('TINYSQUARE_USING_EXAMPLES_TETRIS'):
    src += Glob('tetris/*.c')
    path += [cwd + '/tetris']

group = DefineGroup('TinySquare', src, depend = ['PKG_USING_TINYSQUARE'], CPPPATH = path)

Return('group')
